#!/bin/bash

occurences=`xrandr | grep 'HDMI1 connected'`

if [ ! -z "$occurences" ]; then

    xrandr --output eDP1 --mode 1920x1080 --auto --output HDMI1 --mode 1920x1080 --right-of eDP1 --primary  --auto
    xdotool mousemove 2880 540

fi
